MVC/Models/ApiCallModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class ApiCallModel
    {
        public string output { get; set; }
    }
}

MVC/Controllers/ApiCallController.cs
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApiOwin.Models;

namespace MVC.Controllers
{
    public class ApiCallController : Controller
    {
        // GET: ApiCall
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string key)
        {
            key = key ?? string.Empty;

            HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, "http://localhost:25109/customers/Get");
            string headerKey = string.Format("Hieu : {0}", key);

            requestMessage.Headers.Add("x-company-auth", headerKey);
            HttpClient httpClient = new HttpClient();
            httpClient.Timeout = TimeSpan.FromMinutes(60);

            Task<HttpResponseMessage> httpRequest = httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseContentRead, CancellationToken.None);
            HttpResponseMessage httpResponse = httpRequest.Result;
            HttpStatusCode statusCode = httpResponse.StatusCode;

            StringBuilder output = new StringBuilder();
            output.AppendLine(string.Format("Response status code: {0}", statusCode));

            Debug.WriteLine("Response status code: {0}", statusCode);
            HttpContent responseContent = httpResponse.Content;

            if (responseContent != null)
            {
                Task<String> stringContentsTask = responseContent.ReadAsStringAsync();
                String stringContents = stringContentsTask.Result;
                Debug.WriteLine(stringContents);

                output.AppendLine(stringContents);
            }
            var vm = new ApiCallModel();
            vm.output = output.ToString();

            return View(vm);
        }
    }
}

MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/Views/ApiCall/Index.cshtml
@Model MVC.Models.ApiCallModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    <label>Jquery Call to Anynomous Call</label>
    <button id="anynomous">Anynomous Call.</button>
    <div id="resultA"></div>
</div>

<div>
    <label>Jquery Call to NonAnynomous Call</label>
    <button id="nonAnynomous">NonAnynomous Call.</button>
    <div id="resultB"></div>
</div>
<br />
<div>
    <label>Post To ApiOwin</label>
    @using (Html.BeginForm("Index", "ApiCall", FormMethod.Post))
    {
        <input type="text" id="key" name="key" value="1234"/>
        <button>Post To ApiOwin</button>
    }

    @{ 
        if (Model != null && Model.output != null)
        {
            <label>@Model.output</label>
        }
    }
</div>

@section Scripts
{
    <script type="text/javascript">
        var uri = 'http://localhost:25109/customers/Anonymous';
        var uri2 = 'http://localhost:25109/customers/Get';

        $(document).ready(function () {

            //$('#anynomous').click(function () {

            //    $.ajax({
            //        type: 'GET',
            //        cache: false,
            //        url: uri,
            //        success: function (data) { alert(data[0].Name); }
            //    });
            //});
        });

        

        var demo = (function () {            

            $('#anynomous').click(callAnynomous);
            $('#nonAnynomous').click(callNonAnynomous);

            function callAnynomous() {
                // Send an AJAX request
                $.getJSON(uri)
                    .done(function (data) {
                        alert(data[0].Name);
                    });
            };

            function callNonAnynomous() {
                // Send an AJAX request
                var request = $.ajax({
                    type: 'GET',
                    cache: false,
                    url: uri2                   
                });

                request.done(function (msg) { alert(msg); });

                request.fail(function (jqXHR, textStatus) {
                    alert("Request failed: " + textStatus);
                });
            };

            return {
                CallAnynomous: callAnynomous,
                CallNonAnynomous : callNonAnynomous
            }
        })();
    
    </script>
}

MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">Trying a quick tutorial to get a feel of Owin.</p>
    <p>https://dotnetcodr.com/2015/11/30/wiring-up-a-custom-authentication-method-with-owin-in-web-api-part-5-abstracting-away-the-auth-logic/</p>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hieu's quick demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("ApiCall", "Index", "ApiCall")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>